# Generated by Django 6.0.5 on 2026-06-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green')], default='yellow', max_length=20)),
                ('x_position', models.IntegerField(default=50)),
                ('y_position', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='walls.wall')),
            ],
        ),
    ]
