# Generated by Django 6.0.5 on 2026-06-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='height',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='note',
            name='width',
            field=models.IntegerField(default=220),
        ),
    ]
