# Generated by Django 6.0.5 on 2026-06-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='walls.wall')),
            ],
            options={
                'unique_together': {('wall', 'user')},
            },
        ),
    ]
