# Generated by Django 6.0.5 on 2026-06-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0002_wallmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallmember',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10),
        ),
    ]
